search_box_loc = "//input[@name='q']"
search_result_loc = "//span[contains(text(),'Showing 1 – 24 of')]"
tenth_phone_compare_loc = "(//span[(text()='Add to Compare')])[10]"
eleventh_phone_compare_loc = "(//span[(text()='Add to Compare')])[11]"
compare_box_digit_loc = "(//span[(text()='COMPARE')]//parent::span/following-sibling::div/span)[2]"
price_tenth_phone_loc = "(//div[@class='_3pLy-c row'])[10]/div[2]/div/div/div[1]"
name_tenth_phone_loc = "((//div[@class='_3pLy-c row'])[10]/div/div)[1]"